### PR TITLE
Add readiness probe to wait for bundles to be activated

### PR DESCRIPTION
**Pull request by michaelwittig**
Signed-off-by: Michael Wittig <michael@widdix.de>

### CODE REVIEW

**Comment by michaelwittig** [comment]
@ashutosh-narkar done

**Comment by ashutosh-narkar** [comment]
Thanks @michaelwittig. Lgtm. Can you squash the commits and fix the sign-off ? We can then merge.

**Comment by michaelwittig** [comment]
@ashutosh-narkar done

**Pull request merged**
